---
- name: install docker-py
  pip: name=docker-py version=1.10.6

- name: start a deluge container
  docker_container:
    name: deluge
    #capabilities:
    #  - SYS_PTRACE
    image: kurankat/deluge:latest
    state: started
    read_only: yes
    hostname: "{{ ansible_hostname }}-deluge"
    ports:
      - "{{ deluge_web_port }}:8112"
    restart_policy: always
    volumes:
      - "{{ ext_deluge_download_volume }}:/downloads"
      - "{{ ext_deluge_config_volume }}:/home/user/.config/deluge"
